### ISSUE TITLE
How to install on HA?

### ISSUE THREAD

**Issue by hmichels** [smokyflex/pe1-modbus#1]
Hello smokyflex,
I am a newbie to Home Assistant (HA), so the question: how to install this integration in HA?
An official integration or via HACS is not possible.
Thanks a lot for your help!

Greetings
Holger

**Comment by smokyflex** [comment]
Hi Holger, this project as it is, cannot be integrated into HA, it documents my first DIY efforts to integrate my Fröling boiler into HA via Modbus TCP and MQTT. I am new to HA myself, so I just recently realized that HA offers a builtin Modbus solution: https://www.home-assistant.io/integrations/modbus/, so the whole custom Modbus to MQTT script is not necessary. I have not yet updated this project accordingly. It is unlikely that I will write a working HACS integration for this because I have not the time at the moment. If you have any questions regarding Modbus hardware setup or my Modbus configuration.yaml feel free to contact me!

**Comment by hmichels** [comment]
Hello smokyflex,
Thanks for the feedback!
Yes, I am interested in your Modbus configuration.yaml, because than I have a good starting point ;-)

Regarding Modbus hardware I will follow your suggestion with the "Waveshare Industrial RS232/RS485 to Ethernet Converter". 
**Question:** have you connected the Fröling PE1 to LAN (router) with _1st cable_ for the "Fröling Connect App" **and in addition** the Ethernet Converter to LAN (router) with a _2nd cable_ as well? In total two LAN connections from router to the Fröling PE1?

**Thank you!**

**Comment by smokyflex** [comment]
Hi, I have updated the doc and added 2 yaml files of my working configuration where you should find all you need. 

Regarding your question: Yes I have 2 ethernet connections from my PE1 to the router, one for the Fröling connect service and the second from the Waveshare converter.

Regards, Felix

**Comment by hmichels** [comment]
Great, thank you very much for the information and support. 
This will certainly not only give me a good start. 

Greetings, Holger
